# Generated by Django 3.1.2 on 2021-08-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_sell_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.BooleanField(default=True),
        ),
    ]
