# Generated by Django 3.1.2 on 2021-08-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'مواد غذایی'), (2, 'قهوه های گانودرما'), (3, 'بهداشتی'), (4, 'شوینده بهداشتی'), (5, 'منسوجات'), (6, 'لوازم خانگی'), (7, 'ارایشی'), (8, 'محصولات گشاورزی')], default=1),
        ),
    ]
