# Generated by Django 3.1.2 on 2021-08-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'قهوه های گانودرما'), (2, 'ارایشی'), (3, 'بهداشتی'), (4, 'مواد غذایی'), (5, 'شوینده بهداشتی'), (6, 'منسوجات'), (7, 'لوازم خانگی'), (8, 'محصولات گشاورزی')], default=1),
        ),
    ]
